* Getting Started

This whole repository is available to download. It includes all of the
pretrained models and data necessary for making predictions. If you are familiar
with [[https://git-scm.com/][git]], you can clone this repository from the terminal like so:

: git clone https://github.com/osu-kim-lab/m6Arp

You can also individually download files from the links in the text below.

* Training

#+begin_src shell
python train.py \
       --positive-csv "./data/8975pos_newF1F2GL_fishers0.csv" \
       --negative-csv "./data/8975neg_newF1F2GL_fishers0.csv" \
       --site 8975 \
       --output "new-model.pkl"
#+end_src

* Inference

To predict the presence of a modification, one needs to know the following things:

1. A trained model (For example: [[file:pretrained/model8989.pkl]])
2. A file containing per-read, per-position stats (For example: [[file:data/8989pos_newF1F2GL_fishers0.csv]]). These are generated with Tombo + prsconv3
3. The site at which to make a prediction. The current models enable analysis at 3 m6a sites. These include 8079, 8975, and 8989.

One can then make predictions using our =inference.py= script like so.

#+begin_src shell
python inference.py --model ./pretrained/model8975.pkl \
       --csv ./data/8975pos_newF1F2GL_fishers0.csv \
       --site 8975 \
       --output pred.csv
#+end_src

This will output a csv =pred.csv= with per-read predictions for the presence of
a modification at the specified site for individual reads (read ID provided). An example of this prediction is available
[[file:data/pred.csv][here]].

* Example files
** Models
1. [[file:pretrained/model8079.pkl]]
2. [[file:pretrained/model8975.pkl]]
3. [[file:pretrained/model8989.pkl]]

** Data
1. [[data/8079neg_newF1F2GL_fishers0.csv]]
2. [[data/8079pos_newF1F2GL_fishers0.csv]]
3. [[data/8975neg_newF1F2GL_fishers0.csv]]
4. [[data/8975pos_newF1F2GL_fishers0.csv]]
5. [[data/8989neg_newF1F2GL_fishers0.csv]]
6. [[data/8989pos_newF1F2GL_fishers0.csv]]
